//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBackEndAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aution_table
    {
        public int auc_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public int product_p_id { get; set; }
    
        public virtual product product { get; set; }
    }
}
