//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBackEndAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bid_table
    {
        public int bid_id { get; set; }
        public int usr_id { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> user_bid_price { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    
        public virtual user_db user_db { get; set; }
        public virtual product product { get; set; }
    }
}
