//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBackEndAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.aution_table = new HashSet<aution_table>();
            this.bid_table = new HashSet<bid_table>();
        }
    
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string p_descp { get; set; }
        public Nullable<double> p_size { get; set; }
        public Nullable<double> p_weight { get; set; }
        public string p_material { get; set; }
        public string p_imgloc { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string p_category { get; set; }
        public Nullable<int> usr_id { get; set; }
        public int base_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aution_table> aution_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bid_table> bid_table { get; set; }
        public virtual user_db user_db { get; set; }
    }
}
